#!/usr/bin/env python3
import sys
import subprocess
process = subprocess.Popen(["./csvImport",sys.argv[1],sys.argv[2]], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
out, err = process.communicate()
print(out,err)
