#!/usr/bin/env python3 
import csv
import os 
import sys
import pandas as pd
import mysql.connector
import glob
from subprocess import PIPE, Popen


def cmdline(command):
    process = Popen(
        args=command,
        stdout=PIPE,
        shell=True
    )
    return process.communicate()[0]
from sqlalchemy import create_engine
os.chdir(os.path.dirname(sys.argv[0]))
dbPostfixes=['a','b']
with open('currentDBIndex') as x: currentDBIndex = x.read()
currentDBIndex=1-int(currentDBIndex)
x.close()
with open('db_%s_private.csv' %(dbPostfixes[currentDBIndex]), newline='') as csvfile:
	reader = csv.DictReader(csvfile)
	for row in reader:	
		engine = create_engine('mysql+mysqlconnector://%s:%s@%s/%s' %(row['user'],row['password'],row['host'],row['db']), echo=False)
with open('files.csv', newline='') as csvfile:
	reader = csv.DictReader(csvfile)
	uniqueZips=[]
	tables=[]
	for row in reader:
		tables.append(row['CSV FILE'])
	print ("Table,Rows in CSV,Rows in database slim_%s,Difference" %(dbPostfixes[currentDBIndex]))
	for table in tables:
		result=engine.execute("select count(*) from `%s`" %(table))
		for row in result:
			 db=int(row[0])
		gen=(1 for i in csv.reader(open("./CSV/%s.csv" %(table))))
		csvCount=sum(gen)	
		diff=csvCount-db
		print("%s,%d,%d,%d" %(table,csvCount,db,diff))
