#!/bin/bash
tail -n +2 db_$2_private.postgres.csv | sed -n 1'p' | tr ',' ' ' |while read host db user password;do 
csvsql --db postgresql://$user:$password@$host/$db  ./CSV/$1.csv --insert --overwrite  --tables $1;
done
