#!/bin/bash
tail -n +2 db_${2}_private.csv | sed -n 1'p' | tr ',' ' ' |while read host db user password;do 
csvsql --snifflimit 0 --no-create --db mysql+mysqlconnector://$user:$password@$host/$db --insert ./CSV/$1.csv --tables $1;
done
