#!/bin/bash
tail -n +2 ../db_${2}_private.postgres.csv | sed -n 1'p' | tr ',' ' ' |while read host db user password;do 
csvsql --snifflimit 10000 --db postgresql://$user:$password@$host/$db  ../CSV/$1.csv --tables $1;
done
